version: "2"
services:
    web:
        build: php7.0-fpm-apache
        image: oandermedia/php7.0-fpm-apache
        volumes:
          - /var/www/iStyle-CE:/var/www/html
          - /home/david/.n98-magerun/modules:/usr/local/share/n98-magerun/modules
          - ./log:/var/log/apache2
        ports:
            - 80:80
            - 9999:9999
        links:
            - db
        tty: true

    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 8888:80
        links:
            - db